name: CFBuild
on: 
  push:
    branches:
      - cf-main

env:
  ubuntu_image: "ubuntu:22.04"

jobs:
  macOS-latest:
    runs-on: macOS-latest

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Dependencies
        run: |
          brew update

      - name: Git describe
        id: ghd
        uses: proudust/gh-describe@v2

      - name: Build
        run: |
          ./build-universal-macos11.sh ${{ steps.ghd.outputs.tag }}

      - name: GH Release
        uses: softprops/action-gh-release@v2.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/*.zip
          tag_name: ${{ steps.ghd.outputs.tag }}